# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/Volym0/KTH/ak4/cprog12/lab3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/Volym0/KTH/ak4/cprog12/lab3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/Volym0/KTH/ak4/cprog12/lab3/CMakeFiles /media/Volym0/KTH/ak4/cprog12/lab3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/Volym0/KTH/ak4/cprog12/lab3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

src/action.o: src/action.cpp.o
.PHONY : src/action.o

# target to build an object file
src/action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/action.cpp.o
.PHONY : src/action.cpp.o

src/action.i: src/action.cpp.i
.PHONY : src/action.i

# target to preprocess a source file
src/action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/action.cpp.i
.PHONY : src/action.cpp.i

src/action.s: src/action.cpp.s
.PHONY : src/action.s

# target to generate assembly for a file
src/action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/action.cpp.s
.PHONY : src/action.cpp.s

src/actor.o: src/actor.cpp.o
.PHONY : src/actor.o

# target to build an object file
src/actor.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/actor.cpp.o
.PHONY : src/actor.cpp.o

src/actor.i: src/actor.cpp.i
.PHONY : src/actor.i

# target to preprocess a source file
src/actor.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/actor.cpp.i
.PHONY : src/actor.cpp.i

src/actor.s: src/actor.cpp.s
.PHONY : src/actor.s

# target to generate assembly for a file
src/actor.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/actor.cpp.s
.PHONY : src/actor.cpp.s

src/adverb.o: src/adverb.cpp.o
.PHONY : src/adverb.o

# target to build an object file
src/adverb.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/adverb.cpp.o
.PHONY : src/adverb.cpp.o

src/adverb.i: src/adverb.cpp.i
.PHONY : src/adverb.i

# target to preprocess a source file
src/adverb.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/adverb.cpp.i
.PHONY : src/adverb.cpp.i

src/adverb.s: src/adverb.cpp.s
.PHONY : src/adverb.s

# target to generate assembly for a file
src/adverb.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/adverb.cpp.s
.PHONY : src/adverb.cpp.s

src/alias_action.o: src/alias_action.cpp.o
.PHONY : src/alias_action.o

# target to build an object file
src/alias_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/alias_action.cpp.o
.PHONY : src/alias_action.cpp.o

src/alias_action.i: src/alias_action.cpp.i
.PHONY : src/alias_action.i

# target to preprocess a source file
src/alias_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/alias_action.cpp.i
.PHONY : src/alias_action.cpp.i

src/alias_action.s: src/alias_action.cpp.s
.PHONY : src/alias_action.s

# target to generate assembly for a file
src/alias_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/alias_action.cpp.s
.PHONY : src/alias_action.cpp.s

src/annoyed_npc.o: src/annoyed_npc.cpp.o
.PHONY : src/annoyed_npc.o

# target to build an object file
src/annoyed_npc.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/annoyed_npc.cpp.o
.PHONY : src/annoyed_npc.cpp.o

src/annoyed_npc.i: src/annoyed_npc.cpp.i
.PHONY : src/annoyed_npc.i

# target to preprocess a source file
src/annoyed_npc.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/annoyed_npc.cpp.i
.PHONY : src/annoyed_npc.cpp.i

src/annoyed_npc.s: src/annoyed_npc.cpp.s
.PHONY : src/annoyed_npc.s

# target to generate assembly for a file
src/annoyed_npc.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/annoyed_npc.cpp.s
.PHONY : src/annoyed_npc.cpp.s

src/attack_action.o: src/attack_action.cpp.o
.PHONY : src/attack_action.o

# target to build an object file
src/attack_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/attack_action.cpp.o
.PHONY : src/attack_action.cpp.o

src/attack_action.i: src/attack_action.cpp.i
.PHONY : src/attack_action.i

# target to preprocess a source file
src/attack_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/attack_action.cpp.i
.PHONY : src/attack_action.cpp.i

src/attack_action.s: src/attack_action.cpp.s
.PHONY : src/attack_action.s

# target to generate assembly for a file
src/attack_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/attack_action.cpp.s
.PHONY : src/attack_action.cpp.s

src/border_system.o: src/border_system.cpp.o
.PHONY : src/border_system.o

# target to build an object file
src/border_system.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/border_system.cpp.o
.PHONY : src/border_system.cpp.o

src/border_system.i: src/border_system.cpp.i
.PHONY : src/border_system.i

# target to preprocess a source file
src/border_system.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/border_system.cpp.i
.PHONY : src/border_system.cpp.i

src/border_system.s: src/border_system.cpp.s
.PHONY : src/border_system.s

# target to generate assembly for a file
src/border_system.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/border_system.cpp.s
.PHONY : src/border_system.cpp.s

src/boss.o: src/boss.cpp.o
.PHONY : src/boss.o

# target to build an object file
src/boss.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/boss.cpp.o
.PHONY : src/boss.cpp.o

src/boss.i: src/boss.cpp.i
.PHONY : src/boss.i

# target to preprocess a source file
src/boss.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/boss.cpp.i
.PHONY : src/boss.cpp.i

src/boss.s: src/boss.cpp.s
.PHONY : src/boss.s

# target to generate assembly for a file
src/boss.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/boss.cpp.s
.PHONY : src/boss.cpp.s

src/buy_action.o: src/buy_action.cpp.o
.PHONY : src/buy_action.o

# target to build an object file
src/buy_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/buy_action.cpp.o
.PHONY : src/buy_action.cpp.o

src/buy_action.i: src/buy_action.cpp.i
.PHONY : src/buy_action.i

# target to preprocess a source file
src/buy_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/buy_action.cpp.i
.PHONY : src/buy_action.cpp.i

src/buy_action.s: src/buy_action.cpp.s
.PHONY : src/buy_action.s

# target to generate assembly for a file
src/buy_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/buy_action.cpp.s
.PHONY : src/buy_action.cpp.s

src/consumable_item.o: src/consumable_item.cpp.o
.PHONY : src/consumable_item.o

# target to build an object file
src/consumable_item.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/consumable_item.cpp.o
.PHONY : src/consumable_item.cpp.o

src/consumable_item.i: src/consumable_item.cpp.i
.PHONY : src/consumable_item.i

# target to preprocess a source file
src/consumable_item.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/consumable_item.cpp.i
.PHONY : src/consumable_item.cpp.i

src/consumable_item.s: src/consumable_item.cpp.s
.PHONY : src/consumable_item.s

# target to generate assembly for a file
src/consumable_item.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/consumable_item.cpp.s
.PHONY : src/consumable_item.cpp.s

src/create_alias_action.o: src/create_alias_action.cpp.o
.PHONY : src/create_alias_action.o

# target to build an object file
src/create_alias_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/create_alias_action.cpp.o
.PHONY : src/create_alias_action.cpp.o

src/create_alias_action.i: src/create_alias_action.cpp.i
.PHONY : src/create_alias_action.i

# target to preprocess a source file
src/create_alias_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/create_alias_action.cpp.i
.PHONY : src/create_alias_action.cpp.i

src/create_alias_action.s: src/create_alias_action.cpp.s
.PHONY : src/create_alias_action.s

# target to generate assembly for a file
src/create_alias_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/create_alias_action.cpp.s
.PHONY : src/create_alias_action.cpp.s

src/drop_action.o: src/drop_action.cpp.o
.PHONY : src/drop_action.o

# target to build an object file
src/drop_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/drop_action.cpp.o
.PHONY : src/drop_action.cpp.o

src/drop_action.i: src/drop_action.cpp.i
.PHONY : src/drop_action.i

# target to preprocess a source file
src/drop_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/drop_action.cpp.i
.PHONY : src/drop_action.cpp.i

src/drop_action.s: src/drop_action.cpp.s
.PHONY : src/drop_action.s

# target to generate assembly for a file
src/drop_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/drop_action.cpp.s
.PHONY : src/drop_action.cpp.s

src/galaxy.o: src/galaxy.cpp.o
.PHONY : src/galaxy.o

# target to build an object file
src/galaxy.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/galaxy.cpp.o
.PHONY : src/galaxy.cpp.o

src/galaxy.i: src/galaxy.cpp.i
.PHONY : src/galaxy.i

# target to preprocess a source file
src/galaxy.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/galaxy.cpp.i
.PHONY : src/galaxy.cpp.i

src/galaxy.s: src/galaxy.cpp.s
.PHONY : src/galaxy.s

# target to generate assembly for a file
src/galaxy.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/galaxy.cpp.s
.PHONY : src/galaxy.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/game_object.o: src/game_object.cpp.o
.PHONY : src/game_object.o

# target to build an object file
src/game_object.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game_object.cpp.o
.PHONY : src/game_object.cpp.o

src/game_object.i: src/game_object.cpp.i
.PHONY : src/game_object.i

# target to preprocess a source file
src/game_object.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game_object.cpp.i
.PHONY : src/game_object.cpp.i

src/game_object.s: src/game_object.cpp.s
.PHONY : src/game_object.s

# target to generate assembly for a file
src/game_object.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game_object.cpp.s
.PHONY : src/game_object.cpp.s

src/help_action.o: src/help_action.cpp.o
.PHONY : src/help_action.o

# target to build an object file
src/help_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/help_action.cpp.o
.PHONY : src/help_action.cpp.o

src/help_action.i: src/help_action.cpp.i
.PHONY : src/help_action.i

# target to preprocess a source file
src/help_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/help_action.cpp.i
.PHONY : src/help_action.cpp.i

src/help_action.s: src/help_action.cpp.s
.PHONY : src/help_action.s

# target to generate assembly for a file
src/help_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/help_action.cpp.s
.PHONY : src/help_action.cpp.s

src/hunter.o: src/hunter.cpp.o
.PHONY : src/hunter.o

# target to build an object file
src/hunter.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/hunter.cpp.o
.PHONY : src/hunter.cpp.o

src/hunter.i: src/hunter.cpp.i
.PHONY : src/hunter.i

# target to preprocess a source file
src/hunter.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/hunter.cpp.i
.PHONY : src/hunter.cpp.i

src/hunter.s: src/hunter.cpp.s
.PHONY : src/hunter.s

# target to generate assembly for a file
src/hunter.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/hunter.cpp.s
.PHONY : src/hunter.cpp.s

src/initializers.o: src/initializers.cpp.o
.PHONY : src/initializers.o

# target to build an object file
src/initializers.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/initializers.cpp.o
.PHONY : src/initializers.cpp.o

src/initializers.i: src/initializers.cpp.i
.PHONY : src/initializers.i

# target to preprocess a source file
src/initializers.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/initializers.cpp.i
.PHONY : src/initializers.cpp.i

src/initializers.s: src/initializers.cpp.s
.PHONY : src/initializers.s

# target to generate assembly for a file
src/initializers.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/initializers.cpp.s
.PHONY : src/initializers.cpp.s

src/invalid_action.o: src/invalid_action.cpp.o
.PHONY : src/invalid_action.o

# target to build an object file
src/invalid_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/invalid_action.cpp.o
.PHONY : src/invalid_action.cpp.o

src/invalid_action.i: src/invalid_action.cpp.i
.PHONY : src/invalid_action.i

# target to preprocess a source file
src/invalid_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/invalid_action.cpp.i
.PHONY : src/invalid_action.cpp.i

src/invalid_action.s: src/invalid_action.cpp.s
.PHONY : src/invalid_action.s

# target to generate assembly for a file
src/invalid_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/invalid_action.cpp.s
.PHONY : src/invalid_action.cpp.s

src/inventory_action.o: src/inventory_action.cpp.o
.PHONY : src/inventory_action.o

# target to build an object file
src/inventory_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/inventory_action.cpp.o
.PHONY : src/inventory_action.cpp.o

src/inventory_action.i: src/inventory_action.cpp.i
.PHONY : src/inventory_action.i

# target to preprocess a source file
src/inventory_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/inventory_action.cpp.i
.PHONY : src/inventory_action.cpp.i

src/inventory_action.s: src/inventory_action.cpp.s
.PHONY : src/inventory_action.s

# target to generate assembly for a file
src/inventory_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/inventory_action.cpp.s
.PHONY : src/inventory_action.cpp.s

src/item.o: src/item.cpp.o
.PHONY : src/item.o

# target to build an object file
src/item.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/item.cpp.o
.PHONY : src/item.cpp.o

src/item.i: src/item.cpp.i
.PHONY : src/item.i

# target to preprocess a source file
src/item.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/item.cpp.i
.PHONY : src/item.cpp.i

src/item.s: src/item.cpp.s
.PHONY : src/item.s

# target to generate assembly for a file
src/item.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/item.cpp.s
.PHONY : src/item.cpp.s

src/load_action.o: src/load_action.cpp.o
.PHONY : src/load_action.o

# target to build an object file
src/load_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/load_action.cpp.o
.PHONY : src/load_action.cpp.o

src/load_action.i: src/load_action.cpp.i
.PHONY : src/load_action.i

# target to preprocess a source file
src/load_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/load_action.cpp.i
.PHONY : src/load_action.cpp.i

src/load_action.s: src/load_action.cpp.s
.PHONY : src/load_action.s

# target to generate assembly for a file
src/load_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/load_action.cpp.s
.PHONY : src/load_action.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mayor.o: src/mayor.cpp.o
.PHONY : src/mayor.o

# target to build an object file
src/mayor.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/mayor.cpp.o
.PHONY : src/mayor.cpp.o

src/mayor.i: src/mayor.cpp.i
.PHONY : src/mayor.i

# target to preprocess a source file
src/mayor.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/mayor.cpp.i
.PHONY : src/mayor.cpp.i

src/mayor.s: src/mayor.cpp.s
.PHONY : src/mayor.s

# target to generate assembly for a file
src/mayor.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/mayor.cpp.s
.PHONY : src/mayor.cpp.s

src/merchant.o: src/merchant.cpp.o
.PHONY : src/merchant.o

# target to build an object file
src/merchant.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/merchant.cpp.o
.PHONY : src/merchant.cpp.o

src/merchant.i: src/merchant.cpp.i
.PHONY : src/merchant.i

# target to preprocess a source file
src/merchant.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/merchant.cpp.i
.PHONY : src/merchant.cpp.i

src/merchant.s: src/merchant.cpp.s
.PHONY : src/merchant.s

# target to generate assembly for a file
src/merchant.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/merchant.cpp.s
.PHONY : src/merchant.cpp.s

src/miner.o: src/miner.cpp.o
.PHONY : src/miner.o

# target to build an object file
src/miner.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/miner.cpp.o
.PHONY : src/miner.cpp.o

src/miner.i: src/miner.cpp.i
.PHONY : src/miner.i

# target to preprocess a source file
src/miner.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/miner.cpp.i
.PHONY : src/miner.cpp.i

src/miner.s: src/miner.cpp.s
.PHONY : src/miner.s

# target to generate assembly for a file
src/miner.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/miner.cpp.s
.PHONY : src/miner.cpp.s

src/move_action.o: src/move_action.cpp.o
.PHONY : src/move_action.o

# target to build an object file
src/move_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/move_action.cpp.o
.PHONY : src/move_action.cpp.o

src/move_action.i: src/move_action.cpp.i
.PHONY : src/move_action.i

# target to preprocess a source file
src/move_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/move_action.cpp.i
.PHONY : src/move_action.cpp.i

src/move_action.s: src/move_action.cpp.s
.PHONY : src/move_action.s

# target to generate assembly for a file
src/move_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/move_action.cpp.s
.PHONY : src/move_action.cpp.s

src/npc.o: src/npc.cpp.o
.PHONY : src/npc.o

# target to build an object file
src/npc.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/npc.cpp.o
.PHONY : src/npc.cpp.o

src/npc.i: src/npc.cpp.i
.PHONY : src/npc.i

# target to preprocess a source file
src/npc.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/npc.cpp.i
.PHONY : src/npc.cpp.i

src/npc.s: src/npc.cpp.s
.PHONY : src/npc.s

# target to generate assembly for a file
src/npc.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/npc.cpp.s
.PHONY : src/npc.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/poisoned_system.o: src/poisoned_system.cpp.o
.PHONY : src/poisoned_system.o

# target to build an object file
src/poisoned_system.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/poisoned_system.cpp.o
.PHONY : src/poisoned_system.cpp.o

src/poisoned_system.i: src/poisoned_system.cpp.i
.PHONY : src/poisoned_system.i

# target to preprocess a source file
src/poisoned_system.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/poisoned_system.cpp.i
.PHONY : src/poisoned_system.cpp.i

src/poisoned_system.s: src/poisoned_system.cpp.s
.PHONY : src/poisoned_system.s

# target to generate assembly for a file
src/poisoned_system.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/poisoned_system.cpp.s
.PHONY : src/poisoned_system.cpp.s

src/police.o: src/police.cpp.o
.PHONY : src/police.o

# target to build an object file
src/police.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/police.cpp.o
.PHONY : src/police.cpp.o

src/police.i: src/police.cpp.i
.PHONY : src/police.i

# target to preprocess a source file
src/police.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/police.cpp.i
.PHONY : src/police.cpp.i

src/police.s: src/police.cpp.s
.PHONY : src/police.s

# target to generate assembly for a file
src/police.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/police.cpp.s
.PHONY : src/police.cpp.s

src/quit_action.o: src/quit_action.cpp.o
.PHONY : src/quit_action.o

# target to build an object file
src/quit_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/quit_action.cpp.o
.PHONY : src/quit_action.cpp.o

src/quit_action.i: src/quit_action.cpp.i
.PHONY : src/quit_action.i

# target to preprocess a source file
src/quit_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/quit_action.cpp.i
.PHONY : src/quit_action.cpp.i

src/quit_action.s: src/quit_action.cpp.s
.PHONY : src/quit_action.s

# target to generate assembly for a file
src/quit_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/quit_action.cpp.s
.PHONY : src/quit_action.cpp.s

src/sanctuary_system.o: src/sanctuary_system.cpp.o
.PHONY : src/sanctuary_system.o

# target to build an object file
src/sanctuary_system.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/sanctuary_system.cpp.o
.PHONY : src/sanctuary_system.cpp.o

src/sanctuary_system.i: src/sanctuary_system.cpp.i
.PHONY : src/sanctuary_system.i

# target to preprocess a source file
src/sanctuary_system.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/sanctuary_system.cpp.i
.PHONY : src/sanctuary_system.cpp.i

src/sanctuary_system.s: src/sanctuary_system.cpp.s
.PHONY : src/sanctuary_system.s

# target to generate assembly for a file
src/sanctuary_system.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/sanctuary_system.cpp.s
.PHONY : src/sanctuary_system.cpp.s

src/save_action.o: src/save_action.cpp.o
.PHONY : src/save_action.o

# target to build an object file
src/save_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/save_action.cpp.o
.PHONY : src/save_action.cpp.o

src/save_action.i: src/save_action.cpp.i
.PHONY : src/save_action.i

# target to preprocess a source file
src/save_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/save_action.cpp.i
.PHONY : src/save_action.cpp.i

src/save_action.s: src/save_action.cpp.s
.PHONY : src/save_action.s

# target to generate assembly for a file
src/save_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/save_action.cpp.s
.PHONY : src/save_action.cpp.s

src/scan_action.o: src/scan_action.cpp.o
.PHONY : src/scan_action.o

# target to build an object file
src/scan_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/scan_action.cpp.o
.PHONY : src/scan_action.cpp.o

src/scan_action.i: src/scan_action.cpp.i
.PHONY : src/scan_action.i

# target to preprocess a source file
src/scan_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/scan_action.cpp.i
.PHONY : src/scan_action.cpp.i

src/scan_action.s: src/scan_action.cpp.s
.PHONY : src/scan_action.s

# target to generate assembly for a file
src/scan_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/scan_action.cpp.s
.PHONY : src/scan_action.cpp.s

src/shield.o: src/shield.cpp.o
.PHONY : src/shield.o

# target to build an object file
src/shield.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/shield.cpp.o
.PHONY : src/shield.cpp.o

src/shield.i: src/shield.cpp.i
.PHONY : src/shield.i

# target to preprocess a source file
src/shield.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/shield.cpp.i
.PHONY : src/shield.cpp.i

src/shield.s: src/shield.cpp.s
.PHONY : src/shield.s

# target to generate assembly for a file
src/shield.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/shield.cpp.s
.PHONY : src/shield.cpp.s

src/shield_booster.o: src/shield_booster.cpp.o
.PHONY : src/shield_booster.o

# target to build an object file
src/shield_booster.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/shield_booster.cpp.o
.PHONY : src/shield_booster.cpp.o

src/shield_booster.i: src/shield_booster.cpp.i
.PHONY : src/shield_booster.i

# target to preprocess a source file
src/shield_booster.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/shield_booster.cpp.i
.PHONY : src/shield_booster.cpp.i

src/shield_booster.s: src/shield_booster.cpp.s
.PHONY : src/shield_booster.s

# target to generate assembly for a file
src/shield_booster.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/shield_booster.cpp.s
.PHONY : src/shield_booster.cpp.s

src/solar_system.o: src/solar_system.cpp.o
.PHONY : src/solar_system.o

# target to build an object file
src/solar_system.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/solar_system.cpp.o
.PHONY : src/solar_system.cpp.o

src/solar_system.i: src/solar_system.cpp.i
.PHONY : src/solar_system.i

# target to preprocess a source file
src/solar_system.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/solar_system.cpp.i
.PHONY : src/solar_system.cpp.i

src/solar_system.s: src/solar_system.cpp.s
.PHONY : src/solar_system.s

# target to generate assembly for a file
src/solar_system.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/solar_system.cpp.s
.PHONY : src/solar_system.cpp.s

src/take_action.o: src/take_action.cpp.o
.PHONY : src/take_action.o

# target to build an object file
src/take_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/take_action.cpp.o
.PHONY : src/take_action.cpp.o

src/take_action.i: src/take_action.cpp.i
.PHONY : src/take_action.i

# target to preprocess a source file
src/take_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/take_action.cpp.i
.PHONY : src/take_action.cpp.i

src/take_action.s: src/take_action.cpp.s
.PHONY : src/take_action.s

# target to generate assembly for a file
src/take_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/take_action.cpp.s
.PHONY : src/take_action.cpp.s

src/talk_action.o: src/talk_action.cpp.o
.PHONY : src/talk_action.o

# target to build an object file
src/talk_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/talk_action.cpp.o
.PHONY : src/talk_action.cpp.o

src/talk_action.i: src/talk_action.cpp.i
.PHONY : src/talk_action.i

# target to preprocess a source file
src/talk_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/talk_action.cpp.i
.PHONY : src/talk_action.cpp.i

src/talk_action.s: src/talk_action.cpp.s
.PHONY : src/talk_action.s

# target to generate assembly for a file
src/talk_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/talk_action.cpp.s
.PHONY : src/talk_action.cpp.s

src/use_action.o: src/use_action.cpp.o
.PHONY : src/use_action.o

# target to build an object file
src/use_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/use_action.cpp.o
.PHONY : src/use_action.cpp.o

src/use_action.i: src/use_action.cpp.i
.PHONY : src/use_action.i

# target to preprocess a source file
src/use_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/use_action.cpp.i
.PHONY : src/use_action.cpp.i

src/use_action.s: src/use_action.cpp.s
.PHONY : src/use_action.s

# target to generate assembly for a file
src/use_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/use_action.cpp.s
.PHONY : src/use_action.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/wait_action.o: src/wait_action.cpp.o
.PHONY : src/wait_action.o

# target to build an object file
src/wait_action.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/wait_action.cpp.o
.PHONY : src/wait_action.cpp.o

src/wait_action.i: src/wait_action.cpp.i
.PHONY : src/wait_action.i

# target to preprocess a source file
src/wait_action.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/wait_action.cpp.i
.PHONY : src/wait_action.cpp.i

src/wait_action.s: src/wait_action.cpp.s
.PHONY : src/wait_action.s

# target to generate assembly for a file
src/wait_action.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/wait_action.cpp.s
.PHONY : src/wait_action.cpp.s

src/weapon.o: src/weapon.cpp.o
.PHONY : src/weapon.o

# target to build an object file
src/weapon.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/weapon.cpp.o
.PHONY : src/weapon.cpp.o

src/weapon.i: src/weapon.cpp.i
.PHONY : src/weapon.i

# target to preprocess a source file
src/weapon.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/weapon.cpp.i
.PHONY : src/weapon.cpp.i

src/weapon.s: src/weapon.cpp.s
.PHONY : src/weapon.s

# target to generate assembly for a file
src/weapon.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/weapon.cpp.s
.PHONY : src/weapon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... game"
	@echo "... rebuild_cache"
	@echo "... src/action.o"
	@echo "... src/action.i"
	@echo "... src/action.s"
	@echo "... src/actor.o"
	@echo "... src/actor.i"
	@echo "... src/actor.s"
	@echo "... src/adverb.o"
	@echo "... src/adverb.i"
	@echo "... src/adverb.s"
	@echo "... src/alias_action.o"
	@echo "... src/alias_action.i"
	@echo "... src/alias_action.s"
	@echo "... src/annoyed_npc.o"
	@echo "... src/annoyed_npc.i"
	@echo "... src/annoyed_npc.s"
	@echo "... src/attack_action.o"
	@echo "... src/attack_action.i"
	@echo "... src/attack_action.s"
	@echo "... src/border_system.o"
	@echo "... src/border_system.i"
	@echo "... src/border_system.s"
	@echo "... src/boss.o"
	@echo "... src/boss.i"
	@echo "... src/boss.s"
	@echo "... src/buy_action.o"
	@echo "... src/buy_action.i"
	@echo "... src/buy_action.s"
	@echo "... src/consumable_item.o"
	@echo "... src/consumable_item.i"
	@echo "... src/consumable_item.s"
	@echo "... src/create_alias_action.o"
	@echo "... src/create_alias_action.i"
	@echo "... src/create_alias_action.s"
	@echo "... src/drop_action.o"
	@echo "... src/drop_action.i"
	@echo "... src/drop_action.s"
	@echo "... src/galaxy.o"
	@echo "... src/galaxy.i"
	@echo "... src/galaxy.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/game_object.o"
	@echo "... src/game_object.i"
	@echo "... src/game_object.s"
	@echo "... src/help_action.o"
	@echo "... src/help_action.i"
	@echo "... src/help_action.s"
	@echo "... src/hunter.o"
	@echo "... src/hunter.i"
	@echo "... src/hunter.s"
	@echo "... src/initializers.o"
	@echo "... src/initializers.i"
	@echo "... src/initializers.s"
	@echo "... src/invalid_action.o"
	@echo "... src/invalid_action.i"
	@echo "... src/invalid_action.s"
	@echo "... src/inventory_action.o"
	@echo "... src/inventory_action.i"
	@echo "... src/inventory_action.s"
	@echo "... src/item.o"
	@echo "... src/item.i"
	@echo "... src/item.s"
	@echo "... src/load_action.o"
	@echo "... src/load_action.i"
	@echo "... src/load_action.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mayor.o"
	@echo "... src/mayor.i"
	@echo "... src/mayor.s"
	@echo "... src/merchant.o"
	@echo "... src/merchant.i"
	@echo "... src/merchant.s"
	@echo "... src/miner.o"
	@echo "... src/miner.i"
	@echo "... src/miner.s"
	@echo "... src/move_action.o"
	@echo "... src/move_action.i"
	@echo "... src/move_action.s"
	@echo "... src/npc.o"
	@echo "... src/npc.i"
	@echo "... src/npc.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/poisoned_system.o"
	@echo "... src/poisoned_system.i"
	@echo "... src/poisoned_system.s"
	@echo "... src/police.o"
	@echo "... src/police.i"
	@echo "... src/police.s"
	@echo "... src/quit_action.o"
	@echo "... src/quit_action.i"
	@echo "... src/quit_action.s"
	@echo "... src/sanctuary_system.o"
	@echo "... src/sanctuary_system.i"
	@echo "... src/sanctuary_system.s"
	@echo "... src/save_action.o"
	@echo "... src/save_action.i"
	@echo "... src/save_action.s"
	@echo "... src/scan_action.o"
	@echo "... src/scan_action.i"
	@echo "... src/scan_action.s"
	@echo "... src/shield.o"
	@echo "... src/shield.i"
	@echo "... src/shield.s"
	@echo "... src/shield_booster.o"
	@echo "... src/shield_booster.i"
	@echo "... src/shield_booster.s"
	@echo "... src/solar_system.o"
	@echo "... src/solar_system.i"
	@echo "... src/solar_system.s"
	@echo "... src/take_action.o"
	@echo "... src/take_action.i"
	@echo "... src/take_action.s"
	@echo "... src/talk_action.o"
	@echo "... src/talk_action.i"
	@echo "... src/talk_action.s"
	@echo "... src/use_action.o"
	@echo "... src/use_action.i"
	@echo "... src/use_action.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/wait_action.o"
	@echo "... src/wait_action.i"
	@echo "... src/wait_action.s"
	@echo "... src/weapon.o"
	@echo "... src/weapon.i"
	@echo "... src/weapon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

